language: generic
sudo: false

env:
  global:
    - INSTALL_EDM_VERSION=1.9.1
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - os: linux
      env: RUNTIME=2.7 ETS_TOOLKIT=qt4
    - os: linux
      env: RUNTIME=2.7 ETS_TOOLKIT=wx
    - os: osx
      env: RUNTIME=2.7 ETS_TOOLKIT=qt4

cache:
  directories:
    - $HOME/.cache

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - export DISPLAY=:99.0
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then sh -e /etc/init.d/xvfb start; fi
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./ci/install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./ci/install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install --version ${RUNTIME} -y wheel numpy nose mock Sphinx coverage psutil

install:
  - if [[ ${ETS_TOOLKIT} == 'wx' ]]; then edm install -y wxpython; fi
  - if [[ ${ETS_TOOLKIT} == 'qt4' ]]; then edm install -y pyside; fi
  - edm run -- pip install -r ci/ci-requirements.txt
  - edm run -- pip install vtk
  - edm run -- python -c "import vtk; print(vtk.vtkVersion.GetVTKSourceVersion())"
  - edm run -- python setup.py develop

script:
  - edm run -- coverage erase
  - edm run -- coverage run -p -m nose.core -v tvtk/tests
  - edm run -- coverage run -p -m nose.core -v mayavi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then sh ci/travis-run-integration-tests.sh; fi
  - edm run -- coverage combine

after_success:
  - edm run -- pip install codecov
  - edm run -- codecov
