build: false
shallow_clone: true
environment:

  global:
    PYTHONBUFFERED: "1"
    distutils_use_sdk: 1

cache:
  - c:\temp

init:
  - ps: $Env:path = "C:\Enthought\edm;" + $Env:path
  - ps: $env:ETS_TOOLKIT="qt4"
  - ps: $env:QT_API="pyqt5"

install:
  # Install edm, needed so we can quickly install numpy.
  - ps: Start-FileDownload "https://package-data.enthought.com/edm/win_x86_64/1.9/edm_1.9.1_x86_64.msi"
  - start /wait msiexec /a edm_1.9.1_x86_64.msi /qn /log install.log TARGETDIR=c:\
  - edm info
  - edm install --version 3.6 -y numpy mock Sphinx coverage psutil
  - edm run -- pip install -r travis\travis-requirements.txt
  - edm run -- pip install vtk pyqt5
  - edm run -- python setup.py develop

test_script:
  - edm run -- coverage erase
  - edm run -- coverage run -p -m nose.core -v tvtk/tests
  - edm run -- coverage run -p -m nose.core -v mayavi
  - edm run -- coverage combine
  - edm run -- coverage report
